#include <iostream>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <algorithm>

using namespace std;

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

int evenFibSum(){
    int evensum = 0;
    int num1 = 1;
    int currnum = 2;
    int temp = 0;

    while(currnum < 4000000){ 
        if(currnum % 2 == 0){
            evensum += currnum;
        }
        temp = num1;
        num1 = currnum;
        currnum = currnum + temp;
    }
    
    

    return evensum;
}

int main(){

    cout << evenFibSum() << endl;
    //Correct
}